In [1]:
import pandas as pd
import numpy as np

In [2]:
def load_data(filepath: str) -> pd.DataFrame:
    """Load CSV file into a DataFrame and print a quick summary."""
    df = pd.read_csv(filepath)
    print(f"Loaded '{filepath}'")
    print(f"  Shape : {df.shape}")
    print(f"  Dtypes:\n{df.dtypes}\n")
    return df

In [4]:
load_data('example_dataset.csv')

Loaded 'example_dataset.csv'
  Shape : (100, 5)
  Dtypes:
feature_1    float64
feature_2    float64
feature_3    float64
feature_4    float64
feature_5    float64
dtype: object

    feature_1  feature_2  feature_3  feature_4  feature_5
0    0.978827   0.269072   0.428748   0.610744   0.305823
1    0.516343   0.242067   0.749536   0.066392   0.749588
2    0.419780   0.294532   0.495886   0.623970   0.220129
3    0.696939   0.712466   0.604261   0.515039   0.365214
4    0.844730   0.153239   0.740513   0.906168   0.393810
..        ...        ...        ...        ...        ...
95   0.144670   0.837971   0.624328   0.948671   0.773457
96   0.546457   0.283926   0.165773   0.115892   0.733808
97   0.349668   0.340252   0.517086   0.387780   0.879207
98   0.210824   0.983460   0.135210   0.841077   0.160755
99   0.347368   0.555029   0.743741   0.975033   0.544734

[100 rows x 5 columns]

In [ ]:
def handle_missing_values(df: pd.DataFrame) -> pd.DataFrame:
    """
    Report and handle missing values.
    - Numeric columns: fill with column median.
    - If no missing values, report that and return unchanged.
    """
    missing = df.isnull().sum()
    total_missing = missing.sum()

    if total_missing == 0:
        print("Missing values: none found — no imputation needed.")
    else:
        print(f"Missing values detected:\n{missing[missing > 0]}")
        numeric_cols = df.select_dtypes(include="number").columns
        df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())
        print(f"  → Filled {total_missing} missing value(s) with column medians.")

    return df

In [9]:
handle_missing_values(load_data('example_dataset.csv'))

Loaded 'example_dataset.csv'
  Shape : (100, 5)
  Dtypes:
feature_1    float64
feature_2    float64
feature_3    float64
feature_4    float64
feature_5    float64
dtype: object

Missing values: none found — no imputation needed.

    feature_1  feature_2  feature_3  feature_4  feature_5
0    0.978827   0.269072   0.428748   0.610744   0.305823
1    0.516343   0.242067   0.749536   0.066392   0.749588
2    0.419780   0.294532   0.495886   0.623970   0.220129
3    0.696939   0.712466   0.604261   0.515039   0.365214
4    0.844730   0.153239   0.740513   0.906168   0.393810
..        ...        ...        ...        ...        ...
95   0.144670   0.837971   0.624328   0.948671   0.773457
96   0.546457   0.283926   0.165773   0.115892   0.733808
97   0.349668   0.340252   0.517086   0.387780   0.879207
98   0.210824   0.983460   0.135210   0.841077   0.160755
99   0.347368   0.555029   0.743741   0.975033   0.544734

[100 rows x 5 columns]

In [11]:
def remove_duplicates(df: pd.DataFrame) -> pd.DataFrame:
    """Remove exact duplicate rows and report how many were dropped."""
    before = len(df)
    df = df.drop_duplicates()
    removed = before - len(df)

    if removed == 0:
        print("Duplicates: none found — no rows removed.")
    else:
        print(f"Duplicates: removed {removed} row(s). Rows remaining: {len(df)}")

    return df.reset_index(drop=True)

In [12]:
remove_duplicates(load_data('example_dataset.csv'))

Loaded 'example_dataset.csv'
  Shape : (100, 5)
  Dtypes:
feature_1    float64
feature_2    float64
feature_3    float64
feature_4    float64
feature_5    float64
dtype: object

Duplicates: none found — no rows removed.

    feature_1  feature_2  feature_3  feature_4  feature_5
0    0.978827   0.269072   0.428748   0.610744   0.305823
1    0.516343   0.242067   0.749536   0.066392   0.749588
2    0.419780   0.294532   0.495886   0.623970   0.220129
3    0.696939   0.712466   0.604261   0.515039   0.365214
4    0.844730   0.153239   0.740513   0.906168   0.393810
..        ...        ...        ...        ...        ...
95   0.144670   0.837971   0.624328   0.948671   0.773457
96   0.546457   0.283926   0.165773   0.115892   0.733808
97   0.349668   0.340252   0.517086   0.387780   0.879207
98   0.210824   0.983460   0.135210   0.841077   0.160755
99   0.347368   0.555029   0.743741   0.975033   0.544734

[100 rows x 5 columns]

In [13]:
def preprocess(df: pd.DataFrame) -> pd.DataFrame:
    """Run the full cleaning pipeline."""
    print("\n--- Data Cleaning ---")
    df = handle_missing_values(df)
    df = remove_duplicates(df)
    return df

In [14]:
preprocess(load_data('example_dataset.csv'))

Loaded 'example_dataset.csv'
  Shape : (100, 5)
  Dtypes:
feature_1    float64
feature_2    float64
feature_3    float64
feature_4    float64
feature_5    float64
dtype: object


--- Data Cleaning ---
Missing values: none found — no imputation needed.
Duplicates: none found — no rows removed.

    feature_1  feature_2  feature_3  feature_4  feature_5
0    0.978827   0.269072   0.428748   0.610744   0.305823
1    0.516343   0.242067   0.749536   0.066392   0.749588
2    0.419780   0.294532   0.495886   0.623970   0.220129
3    0.696939   0.712466   0.604261   0.515039   0.365214
4    0.844730   0.153239   0.740513   0.906168   0.393810
..        ...        ...        ...        ...        ...
95   0.144670   0.837971   0.624328   0.948671   0.773457
96   0.546457   0.283926   0.165773   0.115892   0.733808
97   0.349668   0.340252   0.517086   0.387780   0.879207
98   0.210824   0.983460   0.135210   0.841077   0.160755
99   0.347368   0.555029   0.743741   0.975033   0.544734

[100 rows x 5 columns]

In [22]:
def add_row_statistics(df: pd.DataFrame, feature_cols: list) -> pd.DataFrame:
    """Row-wise statistics across all feature columns."""
    df["row_mean"]   = df[feature_cols].mean(axis=1)
    df["row_std"]    = df[feature_cols].std(axis=1)
    df["row_min"]    = df[feature_cols].min(axis=1)
    df["row_max"]    = df[feature_cols].max(axis=1)
    df["row_range"]  = df["row_max"] - df["row_min"]   # spread
    return df

In [30]:
add_row_statistics(load_data('example_dataset.csv'), ['feature_1'])

Loaded 'example_dataset.csv'
  Shape : (100, 5)
  Dtypes:
feature_1    float64
feature_2    float64
feature_3    float64
feature_4    float64
feature_5    float64
dtype: object

,feature_1,feature_2,feature_3,feature_4,feature_5,row_mean,row_std,row_min,row_max,row_range
0,0.978827,0.269072,0.428748,0.610744,0.305823,0.978827,NaN,0.978827,0.978827,0.0
1,0.516343,0.242067,0.749536,0.066392,0.749588,0.516343,NaN,0.516343,0.516343,0.0
2,0.419780,0.294532,0.495886,0.623970,0.220129,0.419780,NaN,0.419780,0.419780,0.0
3,0.696939,0.712466,0.604261,0.515039,0.365214,0.696939,NaN,0.696939,0.696939,0.0
4,0.844730,0.153239,0.740513,0.906168,0.393810,0.844730,NaN,0.844730,0.844730,0.0
...,...,...,...,...,...,...,...,...,...,...
95,0.144670,0.837971,0.624328,0.948671,0.773457,0.144670,NaN,0.144670,0.144670,0.0
96,0.546457,0.283926,0.165773,0.115892,0.733808,0.546457,NaN,0.546457,0.546457,0.0
97,0.349668,0.340252,0.517086,0.387780,0.879207,0.349668,NaN,0.349668,0.349668,0.0
98,0.210824,0.983460,0.135210,0.841077,0.160755,0.210824,NaN,0.210824,0.210824,0.0
99,0.347368,0.555029,0.743741,0.975033,0.544734,0.347368,NaN,0.347368,0.347368,0.0

In [31]:
def add_interaction_terms(df: pd.DataFrame, feature_cols: list) -> pd.DataFrame:
    """Pairwise product interaction terms between features."""
    for i in range(len(feature_cols)):
        for j in range(i + 1, len(feature_cols)):
            a, b = feature_cols[i], feature_cols[j]
            col_name = f"{a}_x_{b}"
            df[col_name] = df[a] * df[b]
    return df

In [33]:
def add_ratio_features(df: pd.DataFrame, feature_cols: list) -> pd.DataFrame:
    """
    Ratio of consecutive features (f1/f2, f2/f3, …).
    Uses a small epsilon to avoid division by zero.
    """
    eps = 1e-9
    for i in range(len(feature_cols) - 1):
        a, b = feature_cols[i], feature_cols[i + 1]
        df[f"{a}_div_{b}"] = df[a] / (df[b] + eps)
    return df

In [34]:
def save_data(df: pd.DataFrame, output_path: str) -> None:
    df.to_csv(output_path, index=False)
    print(f"\nProcessed dataset saved -> '{output_path}'")
    print(f"  Shape: {df.shape}")